name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'Replace Current Tables with New Tables')"
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Read Playstation 5 Compatibility CSV
        id: ps5-csv
        uses: juliangruber/read-file-action@v1
        with:
          path: ./playstation-5-Compatibility.csv
          
      - name: Create Playstation 5 Compatibility MD
        uses: petems/csv-to-md-table-action@master
        id: ps5-csv-table-output
        with:
          csvinput: ${{ steps.ps5-csv.outputs.content }}

      - name: Read USB Passthrough Authentication Device CSV
        id: usb-pt-csv
        uses: juliangruber/read-file-action@v1
        with:
          path: ./usb-passthrough-devices.csv
          
      - name: Create USB Passthrough MD
        uses: petems/csv-to-md-table-action@master
        id: usb-pt-csv-table-output
        with:
          csvinput: ${{ steps.usb-pt-csv.outputs.content }}

      - name: Test output
        run: cat ./table-replace.json
        
      - name: Create JSON
        uses: devops-actions/json-to-file@v1.0.0
        id: create-json
        with:
          filename: 'table-replace.json'
          json: |
            [
              {
                "search": "--Playstation 5 Compatibility Table--", 
                "replace":"${{ steps.ps5-csv-table-output.outputs.markdown-table }}", 
                "eval": true
              },
              {
                "search": "--USB Passthrough Authentication Device Table--",
                "replace": "${{ steps.usb-pt-csv-table-output.outputs.markdown-table }}",
                "eval": true
              }
            ]

      - name: Test output
        run: cat ./table-replace.json

      - name: Replace Text in README
        run: |
          cp TEMPLATE.md README.md
          sed 's/"--Playstation 5 Compatibility Table--"/"${{ steps.ps5-csv-table-output.outputs.markdown-table }}"/' README.md
          sed 's/"--USB Passthrough Authentication Device Table--"/"${{ steps.usb-pt-csv-table-output.outputs.markdown-table }}"/' README.md
      
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Replace Current Tables with New Tables
      # - name: Readme Replacer - Readme-Workflows
      # # uses: Readme-Workflows/readme-replacer@476f6f7ca5f3a0e7d3a55712d70227845ea3c3b6
      #   uses: Readme-Workflows/readme-replacer@v1.0.1
      #   with:
      #     GH_USERNAME: ${{ github.repository_owner }} # optional, default is ${{ github.repository_owner }}
      #     TEMPLATE_FILE: ./TEMPLATE.md # optional, default is ./TEMPLATE.md
      #     COMMIT_FILE: ./README.md # optional, default is ./README.md
      #     CUSTOM_REPLACER_FILE: ./table-replace.json # optional, default is ./.github/customReplacer.json
      #     COMMIT_MESSAGE: "Replace Current Tables with New Tables" # optional, default is ⚡ Update README by replacing keywords
      #     COMMIT_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com # optional, default is 41898282+github-actions[bot]@users.noreply.github.com
      #     COMMIT_NAME: replacer-bot # optional, default is replacer-bot
