name: Update README

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'Replace Current Tables with New Tables')"

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Read Playstation 5 Compatibility CSV
        id: ps5-csv
        uses: juliangruber/read-file-action@v1
        with:
          path: ./playstation-5-Compatibility.csv
          
      - name: Create Playstation 5 Compatibility MD
        uses: petems/csv-to-md-table-action@master
        id: ps5-csv-table-output
        with:
          csvinput: ${{ steps.ps5-csv.outputs.content }}

      - name: Read USB Passthrough Authentication Device CSV
        id: usb-pt-csv
        uses: juliangruber/read-file-action@v1
        with:
          path: ./usb-passthrough-devices.csv
          
      - name: Create USB Passthrough MD
        uses: petems/csv-to-md-table-action@master
        id: usb-pt-csv-table-output
        with:
          csvinput: ${{ steps.usb-pt-csv.outputs.content }}

      - name: Copy TEMPLATE to README
        run: |
          cp TEMPLATE.md README.md

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt

      - name: Run src/replace-tables.py
        run: python src/replace-tables.py
      
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Replace Current Tables with New Tables
